# require the branch name to be master
if: branch = master

language: python
python:
    - "3.7"
    - "3.8"
    - "3.9"

sudo: false
dist: xenial
matrix:
    fast_finish: true
#env:
    #matrix:
        #- NUMPY=1.20 SCIPY=1.5
        #- NUMPY=1.21 SCIPY=1.6
        #- NUMPY=1.22 SCIPY=1.7
        #- NUMPY=1.24 SCIPY=1.10

before_install:
    # Python package manager
    - travis_retry wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"; hash -r
    - conda config --set quiet yes --set always_yes yes --set changeps1 no
    - conda update -q conda
    - travis_retry conda update --name base --channel defaults conda
    - conda info -a

install:
    # runtime dependencies
    - travis_retry conda create -q --name test-env
    - eval "$(conda shell.bash hook)"
    - conda activate test-env
    - conda update --all
    #- travis_retry conda install python=$TRAVIS_PYTHON_VERSION numpy=$NUMPY scipy=$SCIPY
    - travis_retry conda install python=$TRAVIS_PYTHON_VERSION numpy scipy
    - travis_retry conda install --channel conda-forge igraph
    - travis_retry conda install -c conda-forge tox
    # testing dependencies
    # - travis_retry conda install matplotlib basemap sphinx
    # - travis_retry conda install anaconda networkx
    # - travis_retry pip install .[testing]

# before_script:
    # limit pytest processes within container environment
    # - sed -i 's/auto/4/' pytest.ini

script:
    # package
    - pip install -vv -e .

    # test suite
    # (Cython imports dysfunctional inside tox env, unless package installed outside)
    - tox -vvvv

after_success:
    - codecov

notifications:
    email:
        on_success: change
        on_failure: always
